### ISSUE TITLE
5の倍数の時の実装

### ISSUE THREAD

**Issue by dkuyoshi** [dnishio/git-practice#13]
buzzを出力

**Comment by dnishio** [comment]
よろしくお願いします！
綴りミスには気をつけて 👍

**Comment by dkuyoshi** [comment]
SyntaxError: Non-ASCII character '\xe3' in file /Users/dkuyoshi/git-practice/fizzbuzz.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
っていうエラーが出ます

**Comment by dnishio** [comment]
`# coding: UTF-8`をコードの頭につけるとうまく行きますか？

**Comment by dkuyoshi** [comment]
うまく行きました

**Comment by dnishio** [comment]
とりあえず今回はそれでお願いします！
